Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,11 +44,21 @@ jobs:
         # Add sdkmanager to PATH
         export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
 
-        # Install platform-tools, build-tools (with AIDL), and necessary NDK version
-        yes | sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-29" "build-tools;29.0.3" "ndk;21.4.7075529"
+        # Install platform-tools, build-tools (including AIDL), and necessary NDK version
+        yes | sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-29" "build-tools;30.0.3" "ndk;21.4.7075529"
 
         # Verify installation
         sdkmanager --list
+
+    - name: Check AIDL installation
+      run: |
+        echo "Checking AIDL installation..."
+        if ! command -v aidl &> /dev/null; then
+          echo "AIDL could not be found, please install it."
+          exit 1
+        else
+          echo "AIDL is installed and available."
+        fi
 
     - name: Build APK
       run: |
